# Generated by Django 4.2.5 on 2023-09-21 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed_from_date',
            field=models.DateField(default=datetime.date(2023, 9, 21)),
        ),
    ]
